### ISSUE TITLE
Option to not mutate the DOM

### ISSUE THREAD

**Issue by imsnif** [deshiknaves/caret-pos#1]
Hi @deshiknaves - first, thanks for this lib! It really came through for me.

I'm wondering if you'd be open to add an option to not mutate the DOM with a shadow caret when getting an element's offset. Essentially, an option that would not do this: https://github.com/deshiknaves/caret-pos/blob/2e73b471ecb22e3e2d99d0d1a2e4c982ce6fbb88/src/editable.js#L82-L95

The motivation for me is when using this lib in sites (that I do not own, I'll be using it in a browser extension) which listen for DOM mutations (eg. when editing Facebook statuses). With these lines in place, chaos ensues when just getting the offset (elements lose focus, the caret changes position unexpectedly, etc.)

So I was thinking something along the lines of: `offset(el, {noShadowCaret: true})`

I'd be happy to whip up a PR implementing this. Wdyt?

**Comment by deshiknaves** [comment]
I’ll have a deeper look into this tomorrow, just out for the day. I don’t see why no 😊. More than happy for you to raise a PR.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deshiknaves** [comment]
This has been merged. Thanks for you help.
