### ISSUE TITLE
UMD module broken due to hyphen in named export

### ISSUE THREAD

**Issue by SeanBannister** [deshiknaves/caret-pos#14]
Thanks for this project, extremely handy.

I noticed this module provides a UMD module, I grabbed it via the [jsdelivr](https://www.jsdelivr.com/) CDN. However the named export is `caret-pos` and javascript functions can't have hyphens in them, I don't use rollup but I believe the fix would be changing it in rollup.config.js

**Comment by deshiknaves** [comment]
Yep, that would be right. I can sort this out later today. I'll keep you posted

**Comment by deshiknaves** [comment]
I'm going to upgrade some packages and test it out while I'm at it. So probably going to be a day or so. Thanks

**Comment by deshiknaves** [comment]
This has been published
