### ISSUE TITLE
Wrong position for scaled textarea

### ISSUE THREAD

**Issue by nvlled** [deshiknaves/caret-pos#6]
The position is wrong, or understated, when the textarea the font size is scaled. I could just do a workaround myself if only I could find a way to know the if the font is scaled in the textarea.

**Comment by ZiedHf** [comment]
Hey, maybe I get his idea. I think I'm facing the same issue. Let me explain.

Let's start from this use case : 
![image](https://user-images.githubusercontent.com/7974028/48271139-f4703d80-e43b-11e8-9dce-6781d587fa72.png)
As you notice here I have an editor as a long editable iframe.
Everything is fine for this snippet : 
`
      const iframe = document.getElementsByTagName('iframe')[0];
      const body = iframe.contentDocument.body;
      const off = offset(body, { iframe: iframe });
      const frameOffset = getOffset(iframe);
      let offsetoff = cloneDeep(off);
      offsetoff.left += frameOffset.left;
      offsetoff.top += frameOffset.top;
      let iframeDim = cloneDeep(offsetoff);
      iframeDim.top += 25;
      iframeDim.left += 15;
`
I'm able here to get the right position I need inside `iframeDim`.
However, the editor I have is scalable, so for long text it will display a scroll bar. And also I'm working on a page with `height:100%`.
Every time I scale my editor and write long text I expect to get the caret position in regard to the window but I get the caret position in regard to the iframe itself.
Is there any option I forgot to include or a tip about this ?

**Comment by deshiknaves** [comment]
I don’t think that is supported at the moment as in iFrame mode it will come in relation to the iFrame. You can do some calculation as to where that is in regards to the window from the position of the iFrame in the window.

I’ll have a look in more detail. Do you have a working example I can look at? Could you put something on codesandbox?

I’m away for a few days, but I’ll have a look when I’m back.

**Comment by nvlled** [comment]
I'm found a way to fix my problem: I add the css rule to the textarea to prevent font scaling:
```css
textarea {
    text-size-adjust: 100%;
}
```
I don't know if this will help ZiedHf's issue.

**Comment by nvlled** [comment]
I think the problem occurs when the textarea is given a css rule like ```width: 100%```, and the font is automatically scaled.

**Comment by ZiedHf** [comment]
Hey Guys,
Solved by using `scrollTop` attribute.
Thank you @deshiknaves & @nvlled
