### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by sl45sms** [deshiknaves/caret-pos#7]
Congrats its was very useful for me, following is my (incomplete) types for anyone have interest
index.d.ts
```typescript
type Offset = {
    left: number;
    height: number; 
    top: number;
}

type Pos= {
pos: number;
} & Offset

export function position(element: HTMLElement,pos?:number): Pos;
export function offset(element: HTMLElement): Offset;
```
(im not create a PR cause types it's incomplete and i don't want anyone blame me for trashing his/her code)

**Comment by ThreeStonesLee** [comment]
Can I use this in IE 11?
